"""
Data Source Adapters — implementations of the retrieval and enrichment protocols.

In production, these would wrap real APIs (Apollo, Clearbit, ZoomInfo, etc.).
For development and testing, we provide realistic mock implementations that
simulate real-world data characteristics: noise, missing fields, latency.
"""

from __future__ import annotations

import asyncio
import hashlib
import random
import logging
from typing import Any

from src.models.schemas import CompanyRecord, RetrievalFilter

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Company data pools — realistic but synthetic
# ---------------------------------------------------------------------------

_COMPANY_POOL = [
    {
        "name": "NeuralPath AI",
        "domain": "neuralpath.ai",
        "industry": "ai",
        "geography": "us",
        "employee_count": 120,
        "funding_stage": "series_a",
        "funding_total_usd": 18_000_000,
        "founded_year": 2021,
        "description": "AI-powered document processing platform for enterprise workflows.",
    },
    {
        "name": "DataFlow Systems",
        "domain": "dataflow.io",
        "industry": "saas",
        "geography": "us",
        "employee_count": 280,
        "funding_stage": "series_b",
        "funding_total_usd": 45_000_000,
        "founded_year": 2019,
        "description": "Real-time data pipeline orchestration for analytics teams.",
    },
    {
        "name": "CloudScale AI",
        "domain": "cloudscale.ai",
        "industry": "ai",
        "geography": "us",
        "employee_count": 85,
        "funding_stage": "series_a",
        "funding_total_usd": 12_000_000,
        "founded_year": 2022,
        "description": "Automated ML model deployment and monitoring platform.",
    },
    {
        "name": "FinLedger",
        "domain": "finledger.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 350,
        "funding_stage": "series_c",
        "funding_total_usd": 90_000_000,
        "founded_year": 2018,
        "description": "Next-generation payment infrastructure for embedded finance.",
    },
    {
        "name": "SecureOps",
        "domain": "secureops.dev",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 65,
        "funding_stage": "seed",
        "funding_total_usd": 5_000_000,
        "founded_year": 2023,
        "description": "DevSecOps platform with automated vulnerability detection.",
    },
    {
        "name": "GrowthLoop",
        "domain": "growthloop.co",
        "industry": "saas",
        "geography": "us",
        "employee_count": 150,
        "funding_stage": "series_b",
        "funding_total_usd": 35_000_000,
        "founded_year": 2020,
        "description": "Customer data platform for marketing teams with AI segmentation.",
    },
    {
        "name": "Synthera Bio",
        "domain": "synthera.bio",
        "industry": "biotech",
        "geography": "us",
        "employee_count": 200,
        "funding_stage": "series_b",
        "funding_total_usd": 60_000_000,
        "founded_year": 2019,
        "description": "AI-driven drug discovery platform for pharma companies.",
    },
    {
        "name": "StackPilot",
        "domain": "stackpilot.dev",
        "industry": "ai",
        "geography": "us",
        "employee_count": 45,
        "funding_stage": "seed",
        "funding_total_usd": 8_000_000,
        "founded_year": 2023,
        "description": "AI coding assistant for enterprise development teams.",
    },
    {
        "name": "RevOps Central",
        "domain": "revopscentral.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 180,
        "funding_stage": "series_a",
        "funding_total_usd": 22_000_000,
        "founded_year": 2021,
        "description": "Revenue operations platform unifying sales, marketing, and CS data.",
    },
    {
        "name": "Vertex Analytics",
        "domain": "vertexanalytics.io",
        "industry": "ai",
        "geography": "us",
        "employee_count": 95,
        "funding_stage": "series_a",
        "funding_total_usd": 15_000_000,
        "founded_year": 2022,
        "description": "Predictive analytics platform for B2B sales forecasting.",
    },
    {
        "name": "PayBridge",
        "domain": "paybridge.io",
        "industry": "fintech",
        "geography": "uk",
        "employee_count": 220,
        "funding_stage": "series_b",
        "funding_total_usd": 40_000_000,
        "founded_year": 2020,
        "description": "Cross-border payment APIs for global commerce.",
    },
    {
        "name": "InfraHawk",
        "domain": "infrahawk.io",
        "industry": "devtools",
        "geography": "us",
        "employee_count": 70,
        "funding_stage": "series_a",
        "funding_total_usd": 14_000_000,
        "founded_year": 2022,
        "description": "Infrastructure observability for cloud-native applications.",
    },
    {
        "name": "LegalMind AI",
        "domain": "legalmind.ai",
        "industry": "ai",
        "geography": "us",
        "employee_count": 55,
        "funding_stage": "seed",
        "funding_total_usd": 6_000_000,
        "founded_year": 2023,
        "description": "AI-powered contract analysis and legal workflow automation.",
    },
    {
        "name": "Cascade ML",
        "domain": "cascademl.com",
        "industry": "ai",
        "geography": "eu",
        "employee_count": 130,
        "funding_stage": "series_a",
        "funding_total_usd": 20_000_000,
        "founded_year": 2021,
        "description": "MLOps platform for managing end-to-end machine learning pipelines.",
    },
    {
        "name": "QuotaHit",
        "domain": "quotahit.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 110,
        "funding_stage": "series_a",
        "funding_total_usd": 16_000_000,
        "founded_year": 2022,
        "description": "Sales engagement platform with AI-driven sequencing.",
    },
    {
        "name": "TrustVault",
        "domain": "trustvault.io",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 160,
        "funding_stage": "series_b",
        "funding_total_usd": 38_000_000,
        "founded_year": 2020,
        "description": "Zero-trust access management for distributed workforces.",
    },
    {
        "name": "Helix Health",
        "domain": "helixhealth.co",
        "industry": "healthtech",
        "geography": "us",
        "employee_count": 240,
        "funding_stage": "series_b",
        "funding_total_usd": 55_000_000,
        "founded_year": 2019,
        "description": "Patient engagement platform with predictive health analytics.",
    },
    {
        "name": "AutoCRM",
        "domain": "autocrm.ai",
        "industry": "saas",
        "geography": "us",
        "employee_count": 75,
        "funding_stage": "seed",
        "funding_total_usd": 9_000_000,
        "founded_year": 2023,
        "description": "AI-first CRM that auto-enriches contacts and suggests next actions.",
    },
    {
        "name": "Razorpay",
        "domain": "razorpay.com",
        "industry": "fintech",
        "geography": "india",
        "employee_count": 3000,
        "funding_stage": "series_f",
        "funding_total_usd": 740_000_000,
        "founded_year": 2014,
        "description": "Full-stack payments and banking platform for businesses in India.",
    },
    {
        "name": "Postman",
        "domain": "postman.com",
        "industry": "devtools",
        "geography": "india",
        "employee_count": 800,
        "funding_stage": "series_d",
        "funding_total_usd": 433_000_000,
        "founded_year": 2014,
        "description": "API development platform used by millions of developers worldwide.",
    },
    {
        "name": "Freshworks",
        "domain": "freshworks.com",
        "industry": "saas",
        "geography": "india",
        "employee_count": 5200,
        "funding_stage": "ipo",
        "funding_total_usd": 400_000_000,
        "founded_year": 2010,
        "description": "Cloud-based SaaS for customer engagement, IT, and HR management.",
    },
    {
        "name": "Zerodha",
        "domain": "zerodha.com",
        "industry": "fintech",
        "geography": "india",
        "employee_count": 1200,
        "funding_stage": "bootstrapped",
        "funding_total_usd": 0,
        "founded_year": 2010,
        "description": "India's largest retail stockbroker with a tech-first trading platform.",
    },
    {
        "name": "Darwinbox",
        "domain": "darwinbox.com",
        "industry": "saas",
        "geography": "india",
        "employee_count": 600,
        "funding_stage": "series_d",
        "funding_total_usd": 110_000_000,
        "founded_year": 2015,
        "description": "Cloud-native HR tech platform for enterprise workforce management across Asia.",
    },
    {
        "name": "Observe.AI",
        "domain": "observe.ai",
        "industry": "ai",
        "geography": "india",
        "employee_count": 300,
        "funding_stage": "series_b",
        "funding_total_usd": 75_000_000,
        "founded_year": 2017,
        "description": "AI-powered conversation intelligence platform for contact centers.",
    },
    {
        "name": "Haptik",
        "domain": "haptik.ai",
        "industry": "ai",
        "geography": "india",
        "employee_count": 250,
        "funding_stage": "acquired",
        "funding_total_usd": 100_000_000,
        "founded_year": 2013,
        "description": "Conversational AI platform powering enterprise virtual assistants.",
    },
    {
        "name": "Yellow.ai",
        "domain": "yellow.ai",
        "industry": "ai",
        "geography": "india",
        "employee_count": 700,
        "funding_stage": "series_c",
        "funding_total_usd": 102_000_000,
        "founded_year": 2016,
        "description": "Enterprise conversational AI platform for customer and employee automation.",
    },
    {
        "name": "Sarvam AI",
        "domain": "sarvam.ai",
        "industry": "ai",
        "geography": "india",
        "employee_count": 80,
        "funding_stage": "series_a",
        "funding_total_usd": 41_000_000,
        "founded_year": 2023,
        "description": "Building full-stack generative AI for Indian languages and enterprise use.",
    },
    {
        "name": "Krutrim",
        "domain": "krutrim.com",
        "industry": "ai",
        "geography": "india",
        "employee_count": 150,
        "funding_stage": "series_a",
        "funding_total_usd": 50_000_000,
        "founded_year": 2023,
        "description": "India's own AI LLM and cloud platform for multilingual enterprise applications.",
    },
    {
        "name": "BrowserStack",
        "domain": "browserstack.com",
        "industry": "devtools",
        "geography": "india",
        "employee_count": 1000,
        "funding_stage": "series_b",
        "funding_total_usd": 200_000_000,
        "founded_year": 2011,
        "description": "Cloud testing platform for cross-browser and mobile app testing at scale.",
    },
    {
        "name": "Uniphore",
        "domain": "uniphore.com",
        "industry": "ai",
        "geography": "india",
        "employee_count": 500,
        "funding_stage": "series_e",
        "funding_total_usd": 610_000_000,
        "founded_year": 2008,
        "description": "Enterprise AI platform for conversational automation and emotion analytics.",
    },
    {
        "name": "Chargebee",
        "domain": "chargebee.com",
        "industry": "saas",
        "geography": "india",
        "employee_count": 700,
        "funding_stage": "series_g",
        "funding_total_usd": 230_000_000,
        "founded_year": 2011,
        "description": "Subscription billing and revenue management platform for SaaS businesses.",
    },
    {
        "name": "CleverTap",
        "domain": "clevertap.com",
        "industry": "saas",
        "geography": "india",
        "employee_count": 550,
        "funding_stage": "series_d",
        "funding_total_usd": 240_000_000,
        "founded_year": 2013,
        "description": "All-in-one customer engagement and retention platform with AI-powered analytics.",
    },
    # ── Additional AI / ML ──────────────────────────────────────────────────
    {
        "name": "Cohere",
        "domain": "cohere.com",
        "industry": "ai",
        "geography": "us",
        "employee_count": 450,
        "funding_stage": "series_c",
        "funding_total_usd": 445_000_000,
        "founded_year": 2019,
        "description": "Enterprise NLP platform with custom LLMs for search, generation, and classification.",
    },
    {
        "name": "Writer",
        "domain": "writer.com",
        "industry": "ai",
        "geography": "us",
        "employee_count": 200,
        "funding_stage": "series_b",
        "funding_total_usd": 200_000_000,
        "founded_year": 2020,
        "description": "Full-stack generative AI platform purpose-built for enterprise content and workflows.",
    },
    {
        "name": "Glean",
        "domain": "glean.com",
        "industry": "ai",
        "geography": "us",
        "employee_count": 370,
        "funding_stage": "series_e",
        "funding_total_usd": 600_000_000,
        "founded_year": 2019,
        "description": "AI-powered enterprise search and knowledge discovery across all company apps.",
    },
    {
        "name": "Moveworks",
        "domain": "moveworks.com",
        "industry": "ai",
        "geography": "us",
        "employee_count": 500,
        "funding_stage": "series_c",
        "funding_total_usd": 305_000_000,
        "founded_year": 2016,
        "description": "AI copilot for IT and HR support that automates employee service requests.",
    },
    {
        "name": "Navan",
        "domain": "navan.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 3000,
        "funding_stage": "series_g",
        "funding_total_usd": 1_300_000_000,
        "founded_year": 2015,
        "description": "All-in-one travel, expense, and corporate card platform for modern businesses.",
    },
    {
        "name": "Weights & Biases",
        "domain": "wandb.ai",
        "industry": "ai",
        "geography": "us",
        "employee_count": 400,
        "funding_stage": "series_c",
        "funding_total_usd": 250_000_000,
        "founded_year": 2018,
        "description": "MLOps platform for experiment tracking, model versioning, and dataset management.",
    },
    # ── Sales & Revenue ─────────────────────────────────────────────────────
    {
        "name": "Gong",
        "domain": "gong.io",
        "industry": "saas",
        "geography": "us",
        "employee_count": 1500,
        "funding_stage": "series_e",
        "funding_total_usd": 584_000_000,
        "founded_year": 2015,
        "description": "Revenue intelligence platform capturing and analyzing every customer interaction.",
    },
    {
        "name": "Outreach",
        "domain": "outreach.io",
        "industry": "saas",
        "geography": "us",
        "employee_count": 1200,
        "funding_stage": "series_g",
        "funding_total_usd": 489_000_000,
        "founded_year": 2014,
        "description": "Sales execution platform for automating sequences, calls, and deal management.",
    },
    {
        "name": "Apollo.io",
        "domain": "apollo.io",
        "industry": "saas",
        "geography": "us",
        "employee_count": 800,
        "funding_stage": "series_d",
        "funding_total_usd": 251_000_000,
        "founded_year": 2015,
        "description": "B2B data and sales intelligence platform with built-in engagement tools.",
    },
    {
        "name": "Clay",
        "domain": "clay.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 120,
        "funding_stage": "series_b",
        "funding_total_usd": 62_000_000,
        "founded_year": 2017,
        "description": "AI-powered data enrichment and outbound automation tool for GTM teams.",
    },
    {
        "name": "Clari",
        "domain": "clari.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 700,
        "funding_stage": "series_f",
        "funding_total_usd": 450_000_000,
        "founded_year": 2012,
        "description": "Revenue platform for pipeline management, forecasting, and deal execution.",
    },
    # ── Cybersecurity ────────────────────────────────────────────────────────
    {
        "name": "Wiz",
        "domain": "wiz.io",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 1800,
        "funding_stage": "series_e",
        "funding_total_usd": 1_900_000_000,
        "founded_year": 2020,
        "description": "Cloud security platform that identifies risks across multi-cloud environments.",
    },
    {
        "name": "Orca Security",
        "domain": "orca.security",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 500,
        "funding_stage": "series_c",
        "funding_total_usd": 550_000_000,
        "founded_year": 2019,
        "description": "Agentless cloud security platform providing full-stack visibility and risk detection.",
    },
    {
        "name": "Lacework",
        "domain": "lacework.com",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 600,
        "funding_stage": "series_d",
        "funding_total_usd": 1_300_000_000,
        "founded_year": 2015,
        "description": "Data-driven security platform for cloud workloads and containers.",
    },
    {
        "name": "Abnormal Security",
        "domain": "abnormalsecurity.com",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 550,
        "funding_stage": "series_d",
        "funding_total_usd": 284_000_000,
        "founded_year": 2018,
        "description": "AI-native email security platform stopping advanced phishing and BEC attacks.",
    },
    # ── Fintech ──────────────────────────────────────────────────────────────
    {
        "name": "Brex",
        "domain": "brex.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 1100,
        "funding_stage": "series_d",
        "funding_total_usd": 1_200_000_000,
        "founded_year": 2017,
        "description": "Corporate cards, expense management, and spend controls for modern companies.",
    },
    {
        "name": "Ramp",
        "domain": "ramp.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 900,
        "funding_stage": "series_d",
        "funding_total_usd": 750_000_000,
        "founded_year": 2019,
        "description": "Finance automation platform with corporate cards, bill pay, and expense management.",
    },
    {
        "name": "Mercury",
        "domain": "mercury.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 420,
        "funding_stage": "series_b",
        "funding_total_usd": 152_000_000,
        "founded_year": 2017,
        "description": "Banking and financial stack for startups — business accounts, cards, and treasury.",
    },
    {
        "name": "Deel",
        "domain": "deel.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 3500,
        "funding_stage": "series_d",
        "funding_total_usd": 679_000_000,
        "founded_year": 2019,
        "description": "Global payroll, HR, and compliance platform for distributed teams and contractors.",
    },
    {
        "name": "Stripe",
        "domain": "stripe.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 7000,
        "funding_stage": "series_i",
        "funding_total_usd": 2_200_000_000,
        "founded_year": 2010,
        "description": "Global payments and financial infrastructure platform for internet businesses.",
    },
    {
        "name": "Plaid",
        "domain": "plaid.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 800,
        "funding_stage": "series_d",
        "funding_total_usd": 734_000_000,
        "founded_year": 2013,
        "description": "Financial data network connecting consumer bank accounts to fintech apps.",
    },
    {
        "name": "Paysend",
        "domain": "paysend.com",
        "industry": "fintech",
        "geography": "uk",
        "employee_count": 370,
        "funding_stage": "series_b",
        "funding_total_usd": 125_000_000,
        "founded_year": 2017,
        "description": "Global money transfer platform for cross-border payments in 170+ countries.",
    },
    {
        "name": "Paystack",
        "domain": "paystack.com",
        "industry": "fintech",
        "geography": "nigeria",
        "employee_count": 280,
        "funding_stage": "acquired",
        "funding_total_usd": 200_000_000,
        "founded_year": 2015,
        "description": "Payment infrastructure for Africa enabling businesses to accept online payments.",
    },
    {
        "name": "Stax",
        "domain": "staxpayments.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 310,
        "funding_stage": "series_c",
        "funding_total_usd": 108_000_000,
        "founded_year": 2014,
        "description": "Subscription-based payment processing and merchant services platform for SMBs.",
    },
    {
        "name": "Alma",
        "domain": "almapay.com",
        "industry": "fintech",
        "geography": "france",
        "employee_count": 350,
        "funding_stage": "series_c",
        "funding_total_usd": 59_000_000,
        "founded_year": 2018,
        "description": "Buy-now-pay-later solution for European e-commerce merchants.",
    },
    {
        "name": "Payhawk",
        "domain": "payhawk.com",
        "industry": "fintech",
        "geography": "uk",
        "employee_count": 430,
        "funding_stage": "series_b",
        "funding_total_usd": 112_000_000,
        "founded_year": 2018,
        "description": "Spend management and corporate cards platform for European enterprises.",
    },
    {
        "name": "Rippling",
        "domain": "rippling.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 2000,
        "funding_stage": "series_f",
        "funding_total_usd": 1_200_000_000,
        "founded_year": 2016,
        "description": "Workforce management platform unifying HR, IT, and finance in one system.",
    },
    # ── DevTools / Infrastructure ────────────────────────────────────────────
    {
        "name": "Vercel",
        "domain": "vercel.com",
        "industry": "devtools",
        "geography": "us",
        "employee_count": 400,
        "funding_stage": "series_e",
        "funding_total_usd": 313_000_000,
        "founded_year": 2015,
        "description": "Frontend cloud platform for deploying and scaling web applications globally.",
    },
    {
        "name": "Grafana Labs",
        "domain": "grafana.com",
        "industry": "devtools",
        "geography": "us",
        "employee_count": 800,
        "funding_stage": "series_d",
        "funding_total_usd": 440_000_000,
        "founded_year": 2014,
        "description": "Open-source observability platform for metrics, logs, and traces at scale.",
    },
    {
        "name": "Harness",
        "domain": "harness.io",
        "industry": "devtools",
        "geography": "us",
        "employee_count": 900,
        "funding_stage": "series_c",
        "funding_total_usd": 425_000_000,
        "founded_year": 2017,
        "description": "AI-native software delivery platform for CI/CD, feature flags, and cloud costs.",
    },
    {
        "name": "Temporal",
        "domain": "temporal.io",
        "industry": "devtools",
        "geography": "us",
        "employee_count": 280,
        "funding_stage": "series_b",
        "funding_total_usd": 120_000_000,
        "founded_year": 2019,
        "description": "Durable workflow orchestration platform for building reliable distributed systems.",
    },
    # ── Analytics & Data ─────────────────────────────────────────────────────
    {
        "name": "Amplitude",
        "domain": "amplitude.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 700,
        "funding_stage": "ipo",
        "funding_total_usd": 336_000_000,
        "founded_year": 2012,
        "description": "Digital analytics platform for product teams to understand and improve user behavior.",
    },
    {
        "name": "Mixpanel",
        "domain": "mixpanel.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 350,
        "funding_stage": "series_c",
        "funding_total_usd": 77_000_000,
        "founded_year": 2009,
        "description": "Self-serve product analytics platform for analyzing user journeys and retention.",
    },
    {
        "name": "Census",
        "domain": "getcensus.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 90,
        "funding_stage": "series_b",
        "funding_total_usd": 60_000_000,
        "founded_year": 2018,
        "description": "Reverse ETL platform syncing data warehouse data to business tools automatically.",
    },
    # ── HR / People Ops ──────────────────────────────────────────────────────
    {
        "name": "Lattice",
        "domain": "lattice.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 600,
        "funding_stage": "series_f",
        "funding_total_usd": 329_000_000,
        "founded_year": 2015,
        "description": "People management platform for performance reviews, engagement, and compensation.",
    },
    {
        "name": "Leapsome",
        "domain": "leapsome.com",
        "industry": "saas",
        "geography": "eu",
        "employee_count": 200,
        "funding_stage": "series_a",
        "funding_total_usd": 60_000_000,
        "founded_year": 2016,
        "description": "Intelligent people enablement platform for performance, learning, and engagement.",
    },
    # ── EU SaaS ──────────────────────────────────────────────────────────────
    {
        "name": "Personio",
        "domain": "personio.com",
        "industry": "saas",
        "geography": "eu",
        "employee_count": 1800,
        "funding_stage": "series_e",
        "funding_total_usd": 700_000_000,
        "founded_year": 2015,
        "description": "All-in-one HR platform for SMBs managing recruiting, payroll, and HR operations.",
    },
    {
        "name": "Contentful",
        "domain": "contentful.com",
        "industry": "saas",
        "geography": "eu",
        "employee_count": 800,
        "funding_stage": "series_f",
        "funding_total_usd": 330_000_000,
        "founded_year": 2013,
        "description": "Headless CMS platform enabling teams to deliver content across any digital channel.",
    },
    {
        "name": "Pipefy",
        "domain": "pipefy.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 400,
        "funding_stage": "series_c",
        "funding_total_usd": 150_000_000,
        "founded_year": 2015,
        "description": "No-code process management and workflow automation platform for operations teams.",
    },
    # ── Healthcare / HealthTech ───────────────────────────────────────────────
    {
        "name": "Acuity MD",
        "domain": "acuitymd.com",
        "industry": "healthtech",
        "geography": "us",
        "employee_count": 100,
        "funding_stage": "series_b",
        "funding_total_usd": 45_000_000,
        "founded_year": 2019,
        "description": "Market intelligence and targeting platform for medical device companies.",
    },
    {
        "name": "Veeva Systems",
        "domain": "veeva.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 6000,
        "funding_stage": "ipo",
        "funding_total_usd": 0,
        "founded_year": 2007,
        "description": "Cloud software for the global life sciences industry — CRM, data, and regulatory.",
    },
    # ── Early-stage / Series A targets ───────────────────────────────────────
    {
        "name": "Warmly",
        "domain": "warmly.ai",
        "industry": "saas",
        "geography": "us",
        "employee_count": 40,
        "funding_stage": "series_a",
        "funding_total_usd": 21_000_000,
        "founded_year": 2020,
        "description": "AI-powered pipeline orchestration platform that turns website visitors into revenue.",
    },
    {
        "name": "Common Room",
        "domain": "commonroom.io",
        "industry": "saas",
        "geography": "us",
        "employee_count": 60,
        "funding_stage": "series_b",
        "funding_total_usd": 50_000_000,
        "founded_year": 2020,
        "description": "Community-led growth platform for capturing buying signals from digital communities.",
    },
    {
        "name": "Nexus",
        "domain": "nexus.ai",
        "industry": "ai",
        "geography": "us",
        "employee_count": 35,
        "funding_stage": "seed",
        "funding_total_usd": 7_500_000,
        "founded_year": 2023,
        "description": "AI agent platform enabling enterprises to automate complex multi-step workflows.",
    },
    {
        "name": "Sprout AI",
        "domain": "sprout.ai",
        "industry": "ai",
        "geography": "uk",
        "employee_count": 55,
        "funding_stage": "series_a",
        "funding_total_usd": 16_000_000,
        "founded_year": 2022,
        "description": "AI-powered insurance claims automation platform reducing processing time by 80%.",
    },
    {
        "name": "Lexi AI",
        "domain": "lexi.ai",
        "industry": "ai",
        "geography": "us",
        "employee_count": 28,
        "funding_stage": "seed",
        "funding_total_usd": 4_000_000,
        "founded_year": 2024,
        "description": "AI-native document intelligence for legal, compliance, and finance teams.",
    },

    # ── EdTech ───────────────────────────────────────────────────────────────
    {
        "name": "Coursera",
        "domain": "coursera.org",
        "industry": "edtech",
        "geography": "us",
        "employee_count": 1400,
        "funding_stage": "ipo",
        "funding_total_usd": 464_000_000,
        "founded_year": 2012,
        "description": "Online learning platform offering university-level courses and degrees at scale.",
    },
    {
        "name": "Teachable",
        "domain": "teachable.com",
        "industry": "edtech",
        "geography": "us",
        "employee_count": 250,
        "funding_stage": "acquired",
        "funding_total_usd": 10_000_000,
        "founded_year": 2013,
        "description": "Course creation platform for entrepreneurs and creators to sell online education.",
    },
    {
        "name": "Learnerbly",
        "domain": "learnerbly.com",
        "industry": "edtech",
        "geography": "uk",
        "employee_count": 80,
        "funding_stage": "series_a",
        "funding_total_usd": 12_000_000,
        "founded_year": 2016,
        "description": "Workplace learning platform giving employees a curated library of upskilling resources.",
    },
    {
        "name": "Kahoot!",
        "domain": "kahoot.com",
        "industry": "edtech",
        "geography": "eu",
        "employee_count": 600,
        "funding_stage": "ipo",
        "funding_total_usd": 215_000_000,
        "founded_year": 2012,
        "description": "Game-based learning platform for schools and corporate training worldwide.",
    },
    {
        "name": "Eruditus",
        "domain": "eruditus.com",
        "industry": "edtech",
        "geography": "india",
        "employee_count": 2000,
        "funding_stage": "series_e",
        "funding_total_usd": 650_000_000,
        "founded_year": 2010,
        "description": "Executive education platform partnering with top global universities for working professionals.",
    },
    {
        "name": "Skillsoft",
        "domain": "skillsoft.com",
        "industry": "edtech",
        "geography": "us",
        "employee_count": 2500,
        "funding_stage": "ipo",
        "funding_total_usd": 0,
        "founded_year": 1998,
        "description": "Corporate digital learning platform with AI-driven skill development and compliance training.",
    },
    {
        "name": "Mindvalley",
        "domain": "mindvalley.com",
        "industry": "edtech",
        "geography": "singapore",
        "employee_count": 300,
        "funding_stage": "bootstrapped",
        "funding_total_usd": 0,
        "founded_year": 2003,
        "description": "Personal transformation learning platform with courses on wellness, productivity, and mindset.",
    },

    # ── E-Commerce & Retail Tech ─────────────────────────────────────────────
    {
        "name": "Shopify",
        "domain": "shopify.com",
        "industry": "ecommerce",
        "geography": "canada",
        "employee_count": 10000,
        "funding_stage": "ipo",
        "funding_total_usd": 0,
        "founded_year": 2006,
        "description": "Commerce platform powering millions of businesses to sell online and in-store globally.",
    },
    {
        "name": "Yotpo",
        "domain": "yotpo.com",
        "industry": "ecommerce",
        "geography": "us",
        "employee_count": 700,
        "funding_stage": "series_f",
        "funding_total_usd": 425_000_000,
        "founded_year": 2011,
        "description": "eCommerce marketing platform for reviews, loyalty, SMS, and subscriptions.",
    },
    {
        "name": "Gorgias",
        "domain": "gorgias.com",
        "industry": "ecommerce",
        "geography": "us",
        "employee_count": 250,
        "funding_stage": "series_c",
        "funding_total_usd": 97_000_000,
        "founded_year": 2015,
        "description": "Customer support helpdesk built for eCommerce brands on Shopify, BigCommerce, and Magento.",
    },
    {
        "name": "Klaviyo",
        "domain": "klaviyo.com",
        "industry": "ecommerce",
        "geography": "us",
        "employee_count": 1800,
        "funding_stage": "ipo",
        "funding_total_usd": 778_000_000,
        "founded_year": 2012,
        "description": "Email and SMS marketing automation platform purpose-built for eCommerce growth.",
    },
    {
        "name": "Nuvemshop",
        "domain": "nuvemshop.com",
        "industry": "ecommerce",
        "geography": "latam",
        "employee_count": 1200,
        "funding_stage": "series_e",
        "funding_total_usd": 162_000_000,
        "founded_year": 2010,
        "description": "Leading e-commerce platform for SMBs across Latin America with 100k+ active stores.",
    },
    {
        "name": "Recharge",
        "domain": "rechargepayments.com",
        "industry": "ecommerce",
        "geography": "us",
        "employee_count": 400,
        "funding_stage": "series_b",
        "funding_total_usd": 277_000_000,
        "founded_year": 2014,
        "description": "Subscription management and recurring payments platform for direct-to-consumer brands.",
    },

    # ── Logistics & Supply Chain Tech ────────────────────────────────────────
    {
        "name": "Flexport",
        "domain": "flexport.com",
        "industry": "logistics",
        "geography": "us",
        "employee_count": 2800,
        "funding_stage": "series_e",
        "funding_total_usd": 1_300_000_000,
        "founded_year": 2013,
        "description": "Digital freight forwarder and supply chain platform for global trade visibility.",
    },
    {
        "name": "project44",
        "domain": "project44.com",
        "industry": "logistics",
        "geography": "us",
        "employee_count": 900,
        "funding_stage": "series_f",
        "funding_total_usd": 705_000_000,
        "founded_year": 2014,
        "description": "Advanced visibility platform for tracking freight shipments across all modes in real time.",
    },
    {
        "name": "Stord",
        "domain": "stord.com",
        "industry": "logistics",
        "geography": "us",
        "employee_count": 600,
        "funding_stage": "series_d",
        "funding_total_usd": 205_000_000,
        "founded_year": 2015,
        "description": "Cloud supply chain platform combining warehousing, fulfillment, and freight into one network.",
    },
    {
        "name": "Locus",
        "domain": "locus.sh",
        "industry": "logistics",
        "geography": "india",
        "employee_count": 400,
        "funding_stage": "series_c",
        "funding_total_usd": 80_000_000,
        "founded_year": 2015,
        "description": "Dispatch optimization and last-mile delivery intelligence platform for enterprises.",
    },
    {
        "name": "Nuvocargo",
        "domain": "nuvocargo.com",
        "industry": "logistics",
        "geography": "latam",
        "employee_count": 180,
        "funding_stage": "series_b",
        "funding_total_usd": 36_000_000,
        "founded_year": 2019,
        "description": "Digital freight platform streamlining cross-border trucking between the US and Mexico.",
    },
    {
        "name": "Beacon",
        "domain": "beacon.io",
        "industry": "logistics",
        "geography": "uk",
        "employee_count": 200,
        "funding_stage": "series_b",
        "funding_total_usd": 42_000_000,
        "founded_year": 2018,
        "description": "Digital freight forwarding platform for global supply chain teams.",
    },

    # ── Climate Tech / Clean Tech ─────────────────────────────────────────────
    {
        "name": "Watershed",
        "domain": "watershed.com",
        "industry": "climatetech",
        "geography": "us",
        "employee_count": 300,
        "funding_stage": "series_c",
        "funding_total_usd": 270_000_000,
        "founded_year": 2019,
        "description": "Enterprise climate platform for measuring, reducing, and reporting carbon emissions.",
    },
    {
        "name": "Persefoni",
        "domain": "persefoni.com",
        "industry": "climatetech",
        "geography": "us",
        "employee_count": 200,
        "funding_stage": "series_b",
        "funding_total_usd": 101_000_000,
        "founded_year": 2020,
        "description": "Climate management and accounting platform for enterprise carbon footprint disclosure.",
    },
    {
        "name": "Turntide Technologies",
        "domain": "turntide.com",
        "industry": "climatetech",
        "geography": "us",
        "employee_count": 350,
        "funding_stage": "series_c",
        "funding_total_usd": 190_000_000,
        "founded_year": 2013,
        "description": "Smart motor technology and electrification platform reducing industrial energy use.",
    },
    {
        "name": "Pledge",
        "domain": "pledge.io",
        "industry": "climatetech",
        "geography": "uk",
        "employee_count": 60,
        "funding_stage": "series_a",
        "funding_total_usd": 14_000_000,
        "founded_year": 2021,
        "description": "Carbon footprint calculation and offsetting API for travel and financial companies.",
    },
    {
        "name": "Pachama",
        "domain": "pachama.com",
        "industry": "climatetech",
        "geography": "us",
        "employee_count": 90,
        "funding_stage": "series_b",
        "funding_total_usd": 55_000_000,
        "founded_year": 2018,
        "description": "AI-powered forest carbon marketplace verifying reforestation and conservation projects.",
    },

    # ── PropTech / Real Estate Tech ──────────────────────────────────────────
    {
        "name": "Opendoor",
        "domain": "opendoor.com",
        "industry": "proptech",
        "geography": "us",
        "employee_count": 2500,
        "funding_stage": "ipo",
        "funding_total_usd": 1_500_000_000,
        "founded_year": 2014,
        "description": "Digital real estate platform enabling homeowners to buy and sell homes instantly online.",
    },
    {
        "name": "HqO",
        "domain": "hqo.com",
        "industry": "proptech",
        "geography": "us",
        "employee_count": 200,
        "funding_stage": "series_d",
        "funding_total_usd": 119_000_000,
        "founded_year": 2018,
        "description": "Tenant experience platform for commercial real estate buildings and campuses.",
    },
    {
        "name": "Procore",
        "domain": "procore.com",
        "industry": "proptech",
        "geography": "us",
        "employee_count": 4000,
        "funding_stage": "ipo",
        "funding_total_usd": 568_000_000,
        "founded_year": 2002,
        "description": "Construction management software connecting owners, GCs, and subcontractors.",
    },
    {
        "name": "NoBroker",
        "domain": "nobroker.in",
        "industry": "proptech",
        "geography": "india",
        "employee_count": 5000,
        "funding_stage": "series_e",
        "funding_total_usd": 360_000_000,
        "founded_year": 2014,
        "description": "India's largest proptech platform connecting renters and buyers directly without brokers.",
    },
    {
        "name": "Snapdocs",
        "domain": "snapdocs.com",
        "industry": "proptech",
        "geography": "us",
        "employee_count": 300,
        "funding_stage": "series_d",
        "funding_total_usd": 150_000_000,
        "founded_year": 2012,
        "description": "Digital mortgage closing platform streamlining signings between lenders and title companies.",
    },

    # ── Legal Tech ───────────────────────────────────────────────────────────
    {
        "name": "Clio",
        "domain": "clio.com",
        "industry": "legaltech",
        "geography": "canada",
        "employee_count": 900,
        "funding_stage": "series_f",
        "funding_total_usd": 356_000_000,
        "founded_year": 2008,
        "description": "Cloud-based legal practice management software for law firms of all sizes.",
    },
    {
        "name": "Ironclad",
        "domain": "ironcladapp.com",
        "industry": "legaltech",
        "geography": "us",
        "employee_count": 450,
        "funding_stage": "series_e",
        "funding_total_usd": 333_000_000,
        "founded_year": 2014,
        "description": "Digital contracting platform for legal teams to automate contract workflows end-to-end.",
    },
    {
        "name": "LinkSquares",
        "domain": "linksquares.com",
        "industry": "legaltech",
        "geography": "us",
        "employee_count": 200,
        "funding_stage": "series_c",
        "funding_total_usd": 100_000_000,
        "founded_year": 2015,
        "description": "AI-powered contract management platform for in-house legal and finance teams.",
    },
    {
        "name": "Lexion",
        "domain": "lexion.ai",
        "industry": "legaltech",
        "geography": "us",
        "employee_count": 80,
        "funding_stage": "series_b",
        "funding_total_usd": 31_000_000,
        "founded_year": 2018,
        "description": "AI contract management and workflow automation platform for operations teams.",
    },
    {
        "name": "Juro",
        "domain": "juro.com",
        "industry": "legaltech",
        "geography": "uk",
        "employee_count": 100,
        "funding_stage": "series_b",
        "funding_total_usd": 23_000_000,
        "founded_year": 2016,
        "description": "Browser-native contract collaboration platform for legal and business teams.",
    },

    # ── Marketing Tech ───────────────────────────────────────────────────────
    {
        "name": "Iterable",
        "domain": "iterable.com",
        "industry": "martech",
        "geography": "us",
        "employee_count": 600,
        "funding_stage": "series_e",
        "funding_total_usd": 342_000_000,
        "founded_year": 2013,
        "description": "Cross-channel customer communication platform for personalized lifecycle marketing.",
    },
    {
        "name": "Insider",
        "domain": "useinsider.com",
        "industry": "martech",
        "geography": "singapore",
        "employee_count": 1100,
        "funding_stage": "series_d",
        "funding_total_usd": 275_000_000,
        "founded_year": 2012,
        "description": "AI-native growth management platform for multichannel personalization at scale.",
    },
    {
        "name": "Braze",
        "domain": "braze.com",
        "industry": "martech",
        "geography": "us",
        "employee_count": 1700,
        "funding_stage": "ipo",
        "funding_total_usd": 564_000_000,
        "founded_year": 2011,
        "description": "Customer engagement platform delivering relevant, personalized messaging across channels.",
    },
    {
        "name": "Attentive",
        "domain": "attentive.com",
        "industry": "martech",
        "geography": "us",
        "employee_count": 900,
        "funding_stage": "series_e",
        "funding_total_usd": 863_000_000,
        "founded_year": 2016,
        "description": "Conversational commerce and SMS marketing platform for consumer brands.",
    },
    {
        "name": "Mutiny",
        "domain": "mutinyhq.com",
        "industry": "martech",
        "geography": "us",
        "employee_count": 60,
        "funding_stage": "series_b",
        "funding_total_usd": 50_000_000,
        "founded_year": 2018,
        "description": "AI personalization platform for B2B marketers to convert target accounts on their website.",
    },

    # ── Insurtech ────────────────────────────────────────────────────────────
    {
        "name": "Next Insurance",
        "domain": "nextinsurance.com",
        "industry": "insurtech",
        "geography": "us",
        "employee_count": 900,
        "funding_stage": "series_f",
        "funding_total_usd": 881_000_000,
        "founded_year": 2016,
        "description": "AI-driven small business insurance platform offering instant, fully digital coverage.",
    },
    {
        "name": "Tractable",
        "domain": "tractable.ai",
        "industry": "insurtech",
        "geography": "uk",
        "employee_count": 250,
        "funding_stage": "series_e",
        "funding_total_usd": 115_000_000,
        "founded_year": 2014,
        "description": "AI visual damage assessment platform for auto insurance claims and appraisals.",
    },
    {
        "name": "Acko",
        "domain": "acko.com",
        "industry": "insurtech",
        "geography": "india",
        "employee_count": 1400,
        "funding_stage": "series_e",
        "funding_total_usd": 450_000_000,
        "founded_year": 2016,
        "description": "Digital-first insurance company offering low-cost auto and health insurance in India.",
    },
    {
        "name": "Kin Insurance",
        "domain": "kin.com",
        "industry": "insurtech",
        "geography": "us",
        "employee_count": 350,
        "funding_stage": "series_d",
        "funding_total_usd": 216_000_000,
        "founded_year": 2016,
        "description": "Direct-to-consumer home insurance platform for catastrophe-prone markets.",
    },

    # ── Manufacturing & Industrial AI ────────────────────────────────────────
    {
        "name": "Sight Machine",
        "domain": "sightmachine.com",
        "industry": "manufacturing",
        "geography": "us",
        "employee_count": 180,
        "funding_stage": "series_c",
        "funding_total_usd": 77_000_000,
        "founded_year": 2011,
        "description": "Manufacturing analytics platform delivering real-time production insights from factory data.",
    },
    {
        "name": "Parsable",
        "domain": "parsable.com",
        "industry": "manufacturing",
        "geography": "us",
        "employee_count": 150,
        "funding_stage": "series_d",
        "funding_total_usd": 133_000_000,
        "founded_year": 2013,
        "description": "Connected worker platform digitizing frontline operations for industrial manufacturers.",
    },
    {
        "name": "Augury",
        "domain": "augury.com",
        "industry": "manufacturing",
        "geography": "us",
        "employee_count": 300,
        "funding_stage": "series_e",
        "funding_total_usd": 227_000_000,
        "founded_year": 2011,
        "description": "AI machine health platform predicting equipment failures before they cause downtime.",
    },
    {
        "name": "Tulip",
        "domain": "tulip.co",
        "industry": "manufacturing",
        "geography": "us",
        "employee_count": 250,
        "funding_stage": "series_c",
        "funding_total_usd": 121_000_000,
        "founded_year": 2014,
        "description": "No-code operations platform enabling manufacturers to build and deploy frontline apps.",
    },

    # ── Singapore / Southeast Asia ────────────────────────────────────────────
    {
        "name": "Grab",
        "domain": "grab.com",
        "industry": "saas",
        "geography": "singapore",
        "employee_count": 8000,
        "funding_stage": "ipo",
        "funding_total_usd": 10_000_000_000,
        "founded_year": 2012,
        "description": "Southeast Asia's leading superapp for ride-hailing, food delivery, and fintech.",
    },
    {
        "name": "Patsnap",
        "domain": "patsnap.com",
        "industry": "ai",
        "geography": "singapore",
        "employee_count": 900,
        "funding_stage": "series_e",
        "funding_total_usd": 300_000_000,
        "founded_year": 2007,
        "description": "AI-powered R&D intelligence platform connecting innovation data for IP and product teams.",
    },
    {
        "name": "Nium",
        "domain": "nium.com",
        "industry": "fintech",
        "geography": "singapore",
        "employee_count": 1000,
        "funding_stage": "series_d",
        "funding_total_usd": 300_000_000,
        "founded_year": 2014,
        "description": "Global payments infrastructure platform enabling businesses to send, spend, and receive money.",
    },
    {
        "name": "StoreHub",
        "domain": "storehub.com",
        "industry": "ecommerce",
        "geography": "singapore",
        "employee_count": 200,
        "funding_stage": "series_b",
        "funding_total_usd": 25_000_000,
        "founded_year": 2013,
        "description": "Cloud-based retail management and POS platform for restaurants and retailers in Southeast Asia.",
    },
    {
        "name": "Funding Societies",
        "domain": "fundingsocieties.com",
        "industry": "fintech",
        "geography": "singapore",
        "employee_count": 500,
        "funding_stage": "series_c",
        "funding_total_usd": 294_000_000,
        "founded_year": 2015,
        "description": "SME digital financing platform across Singapore, Indonesia, Malaysia, Thailand, and Vietnam.",
    },

    # ── LATAM ────────────────────────────────────────────────────────────────
    {
        "name": "Nubank",
        "domain": "nubank.com.br",
        "industry": "fintech",
        "geography": "latam",
        "employee_count": 8000,
        "funding_stage": "ipo",
        "funding_total_usd": 2_400_000_000,
        "founded_year": 2013,
        "description": "Latin America's largest digital bank serving 85M+ customers in Brazil, Mexico, and Colombia.",
    },
    {
        "name": "Konfio",
        "domain": "konfio.mx",
        "industry": "fintech",
        "geography": "latam",
        "employee_count": 1000,
        "funding_stage": "series_f",
        "funding_total_usd": 500_000_000,
        "founded_year": 2013,
        "description": "Digital financial services platform for Mexican SMBs offering credit, payments, and tools.",
    },
    {
        "name": "Totvs",
        "domain": "totvs.com",
        "industry": "saas",
        "geography": "latam",
        "employee_count": 12000,
        "funding_stage": "ipo",
        "funding_total_usd": 0,
        "founded_year": 1983,
        "description": "Brazil's largest enterprise software company with ERP, HR, and CRM for all business sizes.",
    },
    {
        "name": "Frubana",
        "domain": "frubana.com",
        "industry": "logistics",
        "geography": "latam",
        "employee_count": 2500,
        "funding_stage": "series_c",
        "funding_total_usd": 195_000_000,
        "founded_year": 2018,
        "description": "B2B food supply platform connecting restaurants with producers across Latin America.",
    },

    # ── Canada ────────────────────────────────────────────────────────────────
    {
        "name": "Hootsuite",
        "domain": "hootsuite.com",
        "industry": "martech",
        "geography": "canada",
        "employee_count": 1000,
        "funding_stage": "series_e",
        "funding_total_usd": 250_000_000,
        "founded_year": 2008,
        "description": "Social media management platform for scheduling, analytics, and team collaboration.",
    },
    {
        "name": "Trulioo",
        "domain": "trulioo.com",
        "industry": "fintech",
        "geography": "canada",
        "employee_count": 400,
        "funding_stage": "series_d",
        "funding_total_usd": 474_000_000,
        "founded_year": 2011,
        "description": "Global identity verification platform providing KYC and AML compliance for businesses.",
    },
    {
        "name": "ApplyBoard",
        "domain": "applyboard.com",
        "industry": "edtech",
        "geography": "canada",
        "employee_count": 1200,
        "funding_stage": "series_d",
        "funding_total_usd": 375_000_000,
        "founded_year": 2015,
        "description": "International student recruitment platform connecting students with global schools.",
    },
    {
        "name": "Coveo",
        "domain": "coveo.com",
        "industry": "ai",
        "geography": "canada",
        "employee_count": 800,
        "funding_stage": "ipo",
        "funding_total_usd": 227_000_000,
        "founded_year": 2005,
        "description": "AI-powered search and personalization platform for enterprise websites, portals, and commerce.",
    },

    # ── Australia ─────────────────────────────────────────────────────────────
    {
        "name": "Canva",
        "domain": "canva.com",
        "industry": "saas",
        "geography": "australia",
        "employee_count": 4500,
        "funding_stage": "series_f",
        "funding_total_usd": 572_000_000,
        "founded_year": 2013,
        "description": "Online design and visual communication platform for teams and individuals worldwide.",
    },
    {
        "name": "Atlassian",
        "domain": "atlassian.com",
        "industry": "devtools",
        "geography": "australia",
        "employee_count": 11000,
        "funding_stage": "ipo",
        "funding_total_usd": 0,
        "founded_year": 2002,
        "description": "Enterprise collaboration and software development tools including Jira, Confluence, and Trello.",
    },
    {
        "name": "SafetyCulture",
        "domain": "safetyculture.com",
        "industry": "saas",
        "geography": "australia",
        "employee_count": 900,
        "funding_stage": "series_e",
        "funding_total_usd": 300_000_000,
        "founded_year": 2004,
        "description": "Operations platform for workplace safety inspections, training, and issue reporting.",
    },
    {
        "name": "Airtasker",
        "domain": "airtasker.com",
        "industry": "saas",
        "geography": "australia",
        "employee_count": 250,
        "funding_stage": "ipo",
        "funding_total_usd": 56_000_000,
        "founded_year": 2012,
        "description": "Online marketplace connecting people who need tasks done with skilled local workers.",
    },

    # ── Middle East ───────────────────────────────────────────────────────────
    {
        "name": "Careem",
        "domain": "careem.com",
        "industry": "saas",
        "geography": "uae",
        "employee_count": 1500,
        "funding_stage": "acquired",
        "funding_total_usd": 771_000_000,
        "founded_year": 2012,
        "description": "Super app for ride-hailing, delivery, and digital payments across the MENA region.",
    },
    {
        "name": "Tabby",
        "domain": "tabby.ai",
        "industry": "fintech",
        "geography": "uae",
        "employee_count": 700,
        "funding_stage": "series_d",
        "funding_total_usd": 350_000_000,
        "founded_year": 2019,
        "description": "Buy-now-pay-later and shopping platform for consumers across the Middle East.",
    },
    {
        "name": "Lean Technologies",
        "domain": "leantech.me",
        "industry": "fintech",
        "geography": "uae",
        "employee_count": 150,
        "funding_stage": "series_b",
        "funding_total_usd": 67_000_000,
        "founded_year": 2019,
        "description": "Open banking API infrastructure enabling fintech apps to access financial data across MENA.",
    },
    {
        "name": "Trella",
        "domain": "trella.app",
        "industry": "logistics",
        "geography": "uae",
        "employee_count": 300,
        "funding_stage": "series_b",
        "funding_total_usd": 42_000_000,
        "founded_year": 2018,
        "description": "Digital freight network connecting shippers with carriers across Egypt, Saudi Arabia, and UAE.",
    },

    # ── Germany / DACH ────────────────────────────────────────────────────────
    {
        "name": "Celonis",
        "domain": "celonis.com",
        "industry": "saas",
        "geography": "eu",
        "employee_count": 3000,
        "funding_stage": "series_d",
        "funding_total_usd": 1_600_000_000,
        "founded_year": 2011,
        "description": "Process mining and execution management platform helping companies optimize operations.",
    },
    {
        "name": "Forto",
        "domain": "forto.com",
        "industry": "logistics",
        "geography": "eu",
        "employee_count": 700,
        "funding_stage": "series_d",
        "funding_total_usd": 300_000_000,
        "founded_year": 2016,
        "description": "Digital supply chain and freight forwarding platform for European and Asian trade lanes.",
    },
    {
        "name": "Pricefx",
        "domain": "pricefx.com",
        "industry": "saas",
        "geography": "eu",
        "employee_count": 400,
        "funding_stage": "series_c",
        "funding_total_usd": 120_000_000,
        "founded_year": 2011,
        "description": "Cloud-native pricing software for B2B companies to optimize price setting and management.",
    },
    {
        "name": "Billie",
        "domain": "billie.io",
        "industry": "fintech",
        "geography": "eu",
        "employee_count": 300,
        "funding_stage": "series_c",
        "funding_total_usd": 139_000_000,
        "founded_year": 2016,
        "description": "B2B buy-now-pay-later and invoice financing platform for European business commerce.",
    },

    # ── Micro-SaaS / Seed stage targets ──────────────────────────────────────
    {
        "name": "Grain",
        "domain": "grain.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 25,
        "funding_stage": "seed",
        "funding_total_usd": 4_300_000,
        "founded_year": 2020,
        "description": "AI meeting recording and highlights platform for sales and customer success teams.",
    },
    {
        "name": "Kondo",
        "domain": "kondo.so",
        "industry": "saas",
        "geography": "us",
        "employee_count": 12,
        "funding_stage": "pre_seed",
        "funding_total_usd": 1_200_000,
        "founded_year": 2023,
        "description": "Inbox management tool using AI to triage and prioritize email and Slack for GTM teams.",
    },
    {
        "name": "Replit",
        "domain": "replit.com",
        "industry": "devtools",
        "geography": "us",
        "employee_count": 120,
        "funding_stage": "series_b",
        "funding_total_usd": 97_000_000,
        "founded_year": 2016,
        "description": "Collaborative browser-based IDE and AI coding platform for developers and learners.",
    },
    {
        "name": "Dopt",
        "domain": "dopt.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 18,
        "funding_stage": "seed",
        "funding_total_usd": 3_500_000,
        "founded_year": 2022,
        "description": "Product onboarding and user flow SDK for product teams to build in-app experiences.",
    },
    {
        "name": "Rows",
        "domain": "rows.com",
        "industry": "saas",
        "geography": "eu",
        "employee_count": 55,
        "funding_stage": "series_b",
        "funding_total_usd": 16_000_000,
        "founded_year": 2018,
        "description": "Next-generation spreadsheet with built-in data integrations and AI formulas.",
    },
    {
        "name": "Folk",
        "domain": "folk.app",
        "industry": "saas",
        "geography": "eu",
        "employee_count": 30,
        "funding_stage": "series_a",
        "funding_total_usd": 15_000_000,
        "founded_year": 2020,
        "description": "Lightweight AI-powered CRM for founders and small GTM teams managing relationships.",
    },
    {
        "name": "Amplemarket",
        "domain": "amplemarket.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 70,
        "funding_stage": "series_a",
        "funding_total_usd": 12_000_000,
        "founded_year": 2019,
        "description": "AI-powered sales intelligence and outreach automation for B2B revenue teams.",
    },
    {
        "name": "Superpowered",
        "domain": "superpowered.ai",
        "industry": "ai",
        "geography": "us",
        "employee_count": 15,
        "funding_stage": "seed",
        "funding_total_usd": 2_800_000,
        "founded_year": 2023,
        "description": "AI meeting notes and CRM auto-fill tool for enterprise sales reps and account executives.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PROMPT 1 — "High-growth AI SaaS companies in the US, VP Sales hooks"
    # Target: industry=ai/saas, geography=us, 50-400 emp, series_a/series_b, fast-growing
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Aisera",
        "domain": "aisera.com",
        "industry": "ai",
        "geography": "us",
        "employee_count": 280,
        "funding_stage": "series_d",
        "funding_total_usd": 90_000_000,
        "founded_year": 2017,
        "description": "AI-powered service desk and IT support automation platform for enterprises.",
    },
    {
        "name": "Dust",
        "domain": "dust.tt",
        "industry": "ai",
        "geography": "us",
        "employee_count": 30,
        "funding_stage": "series_a",
        "funding_total_usd": 16_000_000,
        "founded_year": 2022,
        "description": "AI assistant platform letting teams build custom LLM-powered workflows on company data.",
    },
    {
        "name": "Regie.ai",
        "domain": "regie.ai",
        "industry": "ai",
        "geography": "us",
        "employee_count": 90,
        "funding_stage": "series_b",
        "funding_total_usd": 30_000_000,
        "founded_year": 2020,
        "description": "Generative AI platform for sales teams to auto-draft personalized outbound sequences.",
    },
    {
        "name": "Tavus",
        "domain": "tavus.io",
        "industry": "ai",
        "geography": "us",
        "employee_count": 55,
        "funding_stage": "series_a",
        "funding_total_usd": 18_000_000,
        "founded_year": 2020,
        "description": "AI-generated personalized video platform for sales teams to scale 1:1 video outreach.",
    },
    {
        "name": "Tome",
        "domain": "tome.app",
        "industry": "ai",
        "geography": "us",
        "employee_count": 65,
        "funding_stage": "series_b",
        "funding_total_usd": 75_000_000,
        "founded_year": 2020,
        "description": "AI storytelling and presentation platform for sales, marketing, and go-to-market teams.",
    },
    {
        "name": "Sybill",
        "domain": "sybill.ai",
        "industry": "ai",
        "geography": "us",
        "employee_count": 40,
        "funding_stage": "series_a",
        "funding_total_usd": 11_000_000,
        "founded_year": 2021,
        "description": "AI sales assistant that generates CRM summaries, follow-up emails, and deal insights from calls.",
    },
    {
        "name": "Cresta",
        "domain": "cresta.com",
        "industry": "ai",
        "geography": "us",
        "employee_count": 200,
        "funding_stage": "series_c",
        "funding_total_usd": 151_000_000,
        "founded_year": 2017,
        "description": "Real-time AI coaching platform for contact center agents to improve sales and service performance.",
    },
    {
        "name": "Qualified",
        "domain": "qualified.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 180,
        "funding_stage": "series_c",
        "funding_total_usd": 163_000_000,
        "founded_year": 2018,
        "description": "AI pipeline generation platform converting website traffic into qualified sales meetings.",
    },
    {
        "name": "Unify",
        "domain": "unifygtm.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 25,
        "funding_stage": "series_a",
        "funding_total_usd": 20_000_000,
        "founded_year": 2023,
        "description": "AI-powered outbound automation platform combining intent signals with personalized messaging.",
    },
    {
        "name": "11x",
        "domain": "11x.ai",
        "industry": "ai",
        "geography": "us",
        "employee_count": 45,
        "funding_stage": "series_a",
        "funding_total_usd": 24_000_000,
        "founded_year": 2022,
        "description": "AI sales development rep (SDR) that autonomously prospects, researches, and books meetings.",
    },
    {
        "name": "Pocus",
        "domain": "pocus.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 35,
        "funding_stage": "series_a",
        "funding_total_usd": 23_000_000,
        "founded_year": 2021,
        "description": "Product-led sales platform helping revenue teams identify and convert PQL accounts.",
    },
    {
        "name": "Navattic",
        "domain": "navattic.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 30,
        "funding_stage": "series_a",
        "funding_total_usd": 10_000_000,
        "founded_year": 2021,
        "description": "Interactive product demo platform for B2B SaaS companies to convert prospects faster.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PROMPT 2 — "Fintech startups hiring aggressively"
    # Target: industry=fintech, early/mid stage, high hiring velocity, seed–series_b
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Mercury",
        "domain": "mercury.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 550,
        "funding_stage": "series_b",
        "funding_total_usd": 152_000_000,
        "founded_year": 2017,
        "description": "Banking built for startups — checking, savings, treasury, and venture debt in one dashboard.",
    },
    {
        "name": "Jeeves",
        "domain": "tryjeeves.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 200,
        "funding_stage": "series_c",
        "funding_total_usd": 380_000_000,
        "founded_year": 2019,
        "description": "Global spend management and corporate card platform for international startups.",
    },
    {
        "name": "Airbase",
        "domain": "airbase.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 280,
        "funding_stage": "series_c",
        "funding_total_usd": 132_000_000,
        "founded_year": 2017,
        "description": "Spend management platform with corporate cards, bill pay, and approvals for mid-market companies.",
    },
    {
        "name": "Slope",
        "domain": "slope.so",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 60,
        "funding_stage": "series_a",
        "funding_total_usd": 30_000_000,
        "founded_year": 2021,
        "description": "B2B buy-now-pay-later and net terms platform for software and SaaS companies.",
    },
    {
        "name": "Capchase",
        "domain": "capchase.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 160,
        "funding_stage": "series_b",
        "funding_total_usd": 700_000_000,
        "founded_year": 2020,
        "description": "Revenue-based financing platform letting SaaS companies access ARR upfront without dilution.",
    },
    {
        "name": "Mesh Payments",
        "domain": "meshpayments.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 130,
        "funding_stage": "series_b",
        "funding_total_usd": 60_000_000,
        "founded_year": 2018,
        "description": "Travel and spend management platform consolidating all corporate payments into one platform.",
    },
    {
        "name": "Parafin",
        "domain": "parafin.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 85,
        "funding_stage": "series_b",
        "funding_total_usd": 93_000_000,
        "founded_year": 2020,
        "description": "Embedded capital and financial services infrastructure for platforms and marketplaces.",
    },
    {
        "name": "Moov Financial",
        "domain": "moov.io",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 110,
        "funding_stage": "series_b",
        "funding_total_usd": 78_000_000,
        "founded_year": 2018,
        "description": "Open-source money movement infrastructure for developers to embed payments in any app.",
    },
    {
        "name": "Alloy",
        "domain": "alloy.com",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 300,
        "funding_stage": "series_c",
        "funding_total_usd": 181_000_000,
        "founded_year": 2015,
        "description": "Identity decisioning platform automating KYC, AML, and fraud detection for banks and fintechs.",
    },
    {
        "name": "Unit",
        "domain": "unit.co",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 120,
        "funding_stage": "series_c",
        "funding_total_usd": 100_000_000,
        "founded_year": 2019,
        "description": "Embedded banking API platform letting software companies launch financial products quickly.",
    },
    {
        "name": "Novo",
        "domain": "novo.co",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 180,
        "funding_stage": "series_b",
        "funding_total_usd": 135_000_000,
        "founded_year": 2016,
        "description": "SMB banking platform with smart cash flow tools, invoicing, and payment integrations.",
    },
    {
        "name": "Stitch",
        "domain": "stitch.money",
        "industry": "fintech",
        "geography": "us",
        "employee_count": 70,
        "funding_stage": "series_a",
        "funding_total_usd": 25_000_000,
        "founded_year": 2020,
        "description": "Payment and data API infrastructure enabling businesses to link bank accounts across Africa.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PROMPT 3 — "Companies likely to churn competitors, target CTO"
    # Target: mid-size tech companies (50-500 emp) recently funded, using legacy tools,
    #         engineering-heavy, devtools/saas — signals they're re-evaluating their stack
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Retool",
        "domain": "retool.com",
        "industry": "devtools",
        "geography": "us",
        "employee_count": 350,
        "funding_stage": "series_c",
        "funding_total_usd": 145_000_000,
        "founded_year": 2017,
        "description": "Low-code internal tool builder helping engineering teams launch admin panels and dashboards fast.",
    },
    {
        "name": "Incident.io",
        "domain": "incident.io",
        "industry": "devtools",
        "geography": "uk",
        "employee_count": 90,
        "funding_stage": "series_b",
        "funding_total_usd": 56_000_000,
        "founded_year": 2021,
        "description": "Incident management platform replacing legacy on-call tools with modern Slack-native workflows.",
    },
    {
        "name": "LinearB",
        "domain": "linearb.io",
        "industry": "devtools",
        "geography": "us",
        "employee_count": 120,
        "funding_stage": "series_b",
        "funding_total_usd": 50_000_000,
        "founded_year": 2019,
        "description": "Engineering intelligence platform giving CTOs visibility into team performance and delivery.",
    },
    {
        "name": "Cortex",
        "domain": "cortex.io",
        "industry": "devtools",
        "geography": "us",
        "employee_count": 85,
        "funding_stage": "series_b",
        "funding_total_usd": 35_000_000,
        "founded_year": 2019,
        "description": "Internal developer portal and service catalog replacing fragmented engineering documentation.",
    },
    {
        "name": "Port",
        "domain": "getport.io",
        "industry": "devtools",
        "geography": "us",
        "employee_count": 60,
        "funding_stage": "series_a",
        "funding_total_usd": 17_000_000,
        "founded_year": 2021,
        "description": "Developer portal platform replacing Confluence-based wikis with a live software catalog.",
    },
    {
        "name": "Swimlane",
        "domain": "swimlane.com",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 170,
        "funding_stage": "series_c",
        "funding_total_usd": 70_000_000,
        "founded_year": 2014,
        "description": "Security automation and SOAR platform replacing legacy SIEM tools for SOC teams.",
    },
    {
        "name": "Drata",
        "domain": "drata.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 500,
        "funding_stage": "series_c",
        "funding_total_usd": 328_000_000,
        "founded_year": 2020,
        "description": "Automated compliance platform replacing manual SOC 2 and ISO 27001 audit prep.",
    },
    {
        "name": "Vanta",
        "domain": "vanta.com",
        "industry": "saas",
        "geography": "us",
        "employee_count": 450,
        "funding_stage": "series_c",
        "funding_total_usd": 203_000_000,
        "founded_year": 2016,
        "description": "Security compliance automation platform helping companies get SOC 2, ISO, and HIPAA certified.",
    },
    {
        "name": "Merge",
        "domain": "merge.dev",
        "industry": "devtools",
        "geography": "us",
        "employee_count": 75,
        "funding_stage": "series_b",
        "funding_total_usd": 55_000_000,
        "founded_year": 2020,
        "description": "Unified integration API replacing bespoke integrations for HR, ATS, CRM, and accounting data.",
    },
    {
        "name": "Airplane",
        "domain": "airplane.dev",
        "industry": "devtools",
        "geography": "us",
        "employee_count": 45,
        "funding_stage": "series_b",
        "funding_total_usd": 32_000_000,
        "founded_year": 2020,
        "description": "Developer platform for building internal tools and workflows, replacing spreadsheets and scripts.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PROMPT 4 — "Series A cybersecurity companies with 50-200 employees"
    # Target: industry=cybersecurity, funding_stage=series_a, 50-200 employees EXACTLY
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Cyera",
        "domain": "cyera.io",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 150,
        "funding_stage": "series_b",
        "funding_total_usd": 100_000_000,
        "founded_year": 2021,
        "description": "Data security platform discovering and protecting sensitive data across cloud environments.",
    },
    {
        "name": "Upwind Security",
        "domain": "upwind.io",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 90,
        "funding_stage": "series_a",
        "funding_total_usd": 50_000_000,
        "founded_year": 2022,
        "description": "Runtime cloud security platform identifying and prioritizing real exploitable risks in real time.",
    },
    {
        "name": "Astrix Security",
        "domain": "astrix.security",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 70,
        "funding_stage": "series_a",
        "funding_total_usd": 25_000_000,
        "founded_year": 2021,
        "description": "Non-human identity security platform managing API keys, tokens, and service account risks.",
    },
    {
        "name": "Torq",
        "domain": "torq.io",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 110,
        "funding_stage": "series_b",
        "funding_total_usd": 42_000_000,
        "founded_year": 2020,
        "description": "No-code security automation platform for SOC teams to orchestrate complex incident workflows.",
    },
    {
        "name": "Oligo Security",
        "domain": "oligo.security",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 65,
        "funding_stage": "series_a",
        "funding_total_usd": 28_000_000,
        "founded_year": 2022,
        "description": "Application security platform detecting exploited open-source library vulnerabilities at runtime.",
    },
    {
        "name": "Pentera",
        "domain": "pentera.io",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 180,
        "funding_stage": "series_c",
        "funding_total_usd": 145_000_000,
        "founded_year": 2015,
        "description": "Automated security validation platform continuously testing defenses like a real attacker would.",
    },
    {
        "name": "Aembit",
        "domain": "aembit.io",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 55,
        "funding_stage": "series_a",
        "funding_total_usd": 16_000_000,
        "founded_year": 2021,
        "description": "Workload identity and access management platform securing machine-to-machine communications.",
    },
    {
        "name": "Clutch Security",
        "domain": "clutchsecurity.com",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 50,
        "funding_stage": "series_a",
        "funding_total_usd": 20_000_000,
        "founded_year": 2023,
        "description": "Non-human identity security and secrets management platform for cloud-native engineering teams.",
    },
    {
        "name": "Valence Security",
        "domain": "valencesecurity.com",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 75,
        "funding_stage": "series_a",
        "funding_total_usd": 32_000_000,
        "founded_year": 2021,
        "description": "SaaS security platform managing misconfigurations and threats across the SaaS application stack.",
    },
    {
        "name": "Resourcely",
        "domain": "resourcely.io",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 40,
        "funding_stage": "series_a",
        "funding_total_usd": 16_000_000,
        "founded_year": 2022,
        "description": "Cloud infrastructure guardrails platform ensuring engineers provision resources securely by default.",
    },
    {
        "name": "Entro Security",
        "domain": "entro.security",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 60,
        "funding_stage": "series_a",
        "funding_total_usd": 18_000_000,
        "founded_year": 2022,
        "description": "Secrets security platform providing full lifecycle management for API keys, tokens, and credentials.",
    },
    {
        "name": "Zafran",
        "domain": "zafran.io",
        "industry": "cybersecurity",
        "geography": "us",
        "employee_count": 55,
        "funding_stage": "series_a",
        "funding_total_usd": 30_000_000,
        "founded_year": 2022,
        "description": "Risk and exposure management platform correlating vulnerabilities with actual business impact.",
    },
]


# Aliases for fuzzy matching — handles LLM output variations
_INDUSTRY_ALIASES = {
    "ai": ["ai", "artificial intelligence", "machine learning", "ml", "deep learning", "llm", "gen ai", "generative ai", "nlp", "ai/ml", "mlops", "computer vision"],
    "saas": ["saas", "software as a service", "software", "cloud software", "b2b software", "enterprise software", "crm", "hrtech", "hr tech", "sales tech", "revenue", "analytics", "productivity", "collaboration", "no-code", "low-code"],
    "fintech": ["fintech", "financial technology", "finance", "payments", "banking", "expense management", "lending", "bnpl", "buy now pay later", "neobank", "wealth tech", "wealthtech", "open banking"],
    "cybersecurity": ["cybersecurity", "cyber security", "security", "infosec", "cloud security", "devsecops", "identity", "zero trust"],
    "healthtech": ["healthtech", "health tech", "healthcare", "health", "medtech", "med tech", "digital health", "telehealth"],
    "biotech": ["biotech", "biotechnology", "life sciences", "pharma", "drug discovery"],
    "devtools": ["devtools", "developer tools", "dev tools", "infrastructure", "devops", "platform engineering", "ci/cd", "observability", "cloud", "ide", "api"],
    "edtech": ["edtech", "education technology", "ed tech", "e-learning", "elearning", "online learning", "corporate learning", "lms", "upskilling", "training"],
    "ecommerce": ["ecommerce", "e-commerce", "retail tech", "retail", "d2c", "direct to consumer", "dtc", "online retail", "marketplace", "commerce"],
    "logistics": ["logistics", "supply chain", "freight", "shipping", "fulfillment", "last mile", "trucking", "transportation", "delivery"],
    "climatetech": ["climatetech", "climate tech", "cleantech", "clean tech", "sustainability", "carbon", "net zero", "green tech", "greentech", "esg", "climate"],
    "proptech": ["proptech", "property tech", "real estate tech", "real estate", "construction tech", "contech", "built environment"],
    "legaltech": ["legaltech", "legal tech", "legal", "law tech", "contract management", "contracts"],
    "martech": ["martech", "marketing tech", "marketing technology", "marketing", "ad tech", "adtech", "customer engagement", "email marketing", "sms marketing"],
    "insurtech": ["insurtech", "insurance tech", "insurance technology", "insurance"],
    "manufacturing": ["manufacturing", "industrial", "industry 4.0", "iiot", "industrial iot", "factory", "smart manufacturing", "connected worker", "operations"],
}

_GEO_ALIASES = {
    "us": ["us", "usa", "united states", "united states of america", "north america", "america"],
    "uk": ["uk", "united kingdom", "great britain", "england"],
    "eu": ["eu", "europe", "european union", "germany", "france", "netherlands", "spain", "dach", "nordics"],
    "india": ["india", "in", "south asia", "bharat"],
    "singapore": ["singapore", "sg", "southeast asia", "sea", "apac", "asia pacific"],
    "latam": ["latam", "latin america", "brazil", "mexico", "south america", "colombia"],
    "canada": ["canada", "ca", "canadian"],
    "australia": ["australia", "au", "apac", "oceania", "new zealand"],
    "uae": ["uae", "united arab emirates", "dubai", "middle east", "mena", "saudi arabia", "gcc"],
}


def _fuzzy_match(value: str, filter_terms: list[str], aliases: dict[str, list[str]]) -> bool:
    """Check if value matches any filter term, considering aliases."""
    value_lower = value.lower().strip()

    # Direct substring check (bidirectional)
    for term in filter_terms:
        term_lower = term.lower().strip()
        if term_lower in value_lower or value_lower in term_lower:
            return True

    # Alias expansion: find which alias group the value belongs to,
    # then check if any filter term belongs to the same group
    value_groups = set()
    for key, synonyms in aliases.items():
        if value_lower in synonyms or any(value_lower in s or s in value_lower for s in synonyms):
            value_groups.add(key)

    for term in filter_terms:
        term_lower = term.lower().strip()
        for key, synonyms in aliases.items():
            if term_lower in synonyms or any(term_lower in s or s in term_lower for s in synonyms):
                if key in value_groups:
                    return True

    return False


def _matches_filter(company: dict, filters: RetrievalFilter) -> bool:
    """Check if a company matches the given filters with fuzzy matching."""
    if filters.industry:
        industry = company.get("industry") or ""
        if not _fuzzy_match(industry, filters.industry, _INDUSTRY_ALIASES):
            # Also check description for industry keywords
            desc = (company.get("description") or "").lower()
            if not any(ind.lower() in desc for ind in filters.industry):
                return False

    if filters.geography:
        geo = company.get("geography") or ""
        if not _fuzzy_match(geo, filters.geography, _GEO_ALIASES):
            return False

    if filters.employee_range:
        emp = company.get("employee_count")
        if emp is not None:
            lo, hi = filters.employee_range
            if emp < lo or emp > hi:
                return False

    if filters.funding_stage:
        stage = (company.get("funding_stage") or "").lower()
        if stage not in [s.lower().replace(" ", "_") for s in filters.funding_stage]:
            return False

    if filters.keywords:
        desc = (company.get("description") or "").lower() + " " + (company.get("name") or "").lower()
        if not any(kw.lower() in desc for kw in filters.keywords):
            return False

    if filters.founded_after:
        year = company.get("founded_year")
        if year is not None and year < filters.founded_after:
            return False

    return True


class MockDataSource:
    """
    Simulates a company database / API for development.
    Adds realistic latency and occasional failures.
    """

    def __init__(self, source_name: str = "mock_db", failure_rate: float = 0.05):
        self.source_name = source_name
        self.failure_rate = failure_rate

    async def search(self, filters: RetrievalFilter) -> list[CompanyRecord]:
        # Simulate API latency (200ms-1.5s)
        await asyncio.sleep(random.uniform(0.2, 1.5))

        # Simulate occasional failures
        if random.random() < self.failure_rate:
            raise ConnectionError(f"{self.source_name}: simulated API timeout")

        matches = [c for c in _COMPANY_POOL if _matches_filter(c, filters)]

        # Convert to CompanyRecord, adding noise
        records = []
        for c in matches:
            # 10% chance of missing some fields (simulates incomplete API data)
            record_data = dict(c)
            if random.random() < 0.1:
                record_data["employee_count"] = None
            if random.random() < 0.15:
                record_data["funding_total_usd"] = None

            # Add slight noise to employee count
            if record_data.get("employee_count"):
                noise = random.randint(-5, 10)
                record_data["employee_count"] = max(1, record_data["employee_count"] + noise)

            records.append(CompanyRecord(
                name=record_data["name"],
                domain=record_data.get("domain"),
                industry=record_data.get("industry"),
                geography=record_data.get("geography"),
                employee_count=record_data.get("employee_count"),
                funding_stage=record_data.get("funding_stage"),
                funding_total_usd=record_data.get("funding_total_usd"),
                founded_year=record_data.get("founded_year"),
                description=record_data.get("description"),
                source=self.source_name,
            ))

        return records


class MockSecondarySource:
    """
    A second data source with different (overlapping) data.
    Demonstrates multi-source deduplication in the retrieval agent.
    """

    def __init__(self):
        self.source_name = "mock_secondary"

    async def search(self, filters: RetrievalFilter) -> list[CompanyRecord]:
        await asyncio.sleep(random.uniform(0.3, 1.0))

        # This source has a smaller pool and sometimes different data
        matches = [c for c in _COMPANY_POOL[:25] if _matches_filter(c, filters)]

        records = []
        for c in matches:
            records.append(CompanyRecord(
                name=c["name"],
                domain=c.get("domain"),
                industry=c.get("industry"),
                geography=c.get("geography"),
                employee_count=c.get("employee_count"),
                funding_stage=c.get("funding_stage"),
                description=c.get("description"),
                source=self.source_name,
            ))

        return records
